artifacts_root: artifacts  

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data:https://drive.google.com/file/d/1DFBOk3-dOz4uC-6fbpZDGB9jysTNNDdr/view?usp=sharing
  local_data_file:artifacts/data_ingestion/data.zip 
  unzip_dir:artifacts/data_ingestion
  